### ISSUE TITLE
Plugin installs fail when `asdf_path` is set

### ISSUE THREAD

**Issue by phueac** [sobolevn/dotbot-asdf#10]
Hi! First off, thanks for making this great plugin!

I am using this to bootstrap my system using `asdf` as part of my dotbot `install` script.
With the below code in my `install.conf.yaml`,
```yaml
- asdf:
  - asdf_path: $HOME/.asdf/asdf.sh
  - plugin: awscli
    url: https://github.com/MetricMike/asdf-awscli.git
    global: 2.13.7
    versions:
      - 2.13.7
```
I get this error:
```shell
/bin/sh: 1: source not found
Unknown plugin: aws-vault
Please provide URL
```
I think this is because in https://github.com/sobolevn/dotbot-asdf/blob/3153c946e82f53dd6175af79710ff919ee696842/asdf.py#L111-L112 the code assumes you are running in a shell which has the `source` command available, but in https://github.com/sobolevn/dotbot-asdf/blob/3153c946e82f53dd6175af79710ff919ee696842/asdf.py#L114 `subprocess.Popen` uses the `sh` shell by default, which does not have `source`.

This could be fixed by specifying the shell executable directly, e.g. for `bash`:
```python
 p = subprocess.Popen(command, cwd=self.cwd, shell=True, executable="/bin/bash", **kwargs) 
```

I'm happy to make a PR to fix this, but wanted to check with you how you would prefer to fix this. Should we let the user specify a shell somehow?

Incidentally, I think this is the same issue the poster in #5 was having, and this fix should fix their issue too. Thanks!
