### ISSUE TITLE
Global option

### ISSUE THREAD

**Issue by jamesstidard** [sobolevn/dotbot-asdf#3]
Hi,

Just wondering if you'd be open to adding / accepting a pull request to also set the global `asdf` version?

Something like:

```
- asdf:
  - plugin: python
    url: https://github.com/tuvistavie/asdf-python.git
    global: 3.7.4
    versions:
      - 3.7.4
```

Thanks for the plugin.
