### ISSUE TITLE
Global Version not set correctly

### ISSUE THREAD

**Issue by pecigonzalo** [sobolevn/dotbot-asdf#6]
Given 
```
- asdf:
    - plugin: terraform
      global: 0.11.14
      versions:
        - 0.11.14
        - 0.12.21
```

I get 
```
Installing terraform
Installing terraform plugin
Plugin named terraform already added
Installing terraform 0.11.14
terraform 0.11.14 is already installed
Installing terraform 0.12.21
terraform 0.12.21 is already installed
Setting global terraform 0.12.21```

I believe its due to this section
```
 if "global" in plugin:
                self._run_command(
                    "asdf global {} {}".format(language, version),
                    "Setting global {} {}".format(language, version),
                    "Failed setting global: {} {}".format(language, version),
                )

```

Not actually getting the version from the global parameter as described in the documentation.
